installers:
  - name: asdf
  - name: nvm
  - name: pyenv
  - name: pipx
  - name: sdk
  - name: tfenv

packages:
  - name: zsh
  - name: git
  - name: pre-commit
  - name: dos2unix
  - name: jq
  - name: yq
  - name: unzip
  - name: coreutils
  - name: direnv
  - name: curl
  - name: awscli
  - name: gpg
  - name: bison
  - name: gnu-tar	
  - name: zlib
  - name: checkov
  - name: terraform-docs
  - name: terragrunt
  - name: terrascan
  - name: tflint
  - name: tfsec
  - name: infracost
  - name: poetry
    installer: pipx
    version: 1.1.7
  - name: aws-sso-credential-process
    installer: pipx
  - name: gcloud
    installer: asdf
  - name: helm
    installer: asdf
    version: 3.3.4
  - name: kubectl
    installer: asdf
    version: 1.21.1
  - name: packer
    installer: asdf
    version: 1.6.4
  - name: terraform
    installer: tfenv
    version: 0.12.31
  - name: nodejs
    installer: nvm
    version: 14.13.0
  - name: python
    installer: pyenv
    version: 3.7.10

#  - name: helmsman
#    installer: asdf
#    version: 3.4.4
#    repository: helmsman
#    repository-url: https://github.com/jkrukoff-cb/asdf-helmsman.git
#  - name: ruby
#    installer: asdf
#    version: 2.7.1
#  - name: golang
#    installer: asdf
#    version: 1.15.2
#  - name: serverless
#    installer: npm
#    version: 2.4.0
#  - name: java
#    installer: asdf
